### ISSUE TITLE
main.py를 실행 관련 (pickle 파일 손상?)

### ISSUE THREAD

**Issue by wglee92** [monologg/naver-nlp-challenge-2018#1]
안녕하세요!
저는 nlp 관련 공부를 하고 있는 학생입니다!

네이버 창원대 컴피티션 관련하여 자료를 보다가
선배님의 코드를 보게 되었는데요!
 
README.md 파일을 보고 진행하고 있는데
아래와 같은 에러 문구가 나왔습니다.
utils.py 내의 경로도 수정하고 나름 방법을 찾아보았는데... 
해결이 안되고 있습니다.... ㅜㅜ
혹시 어떤 문제인지 알 수 있을까요? 
![image](https://user-images.githubusercontent.com/27959097/61430174-a095ec80-a918-11e9-8f34-5b2860b2264f.png)

**Comment by monologg** [comment]
* 일단 환경은 Windows 10으로 급하게 한번 테스트해보았는데요(python3.6.6, tensorflow 1.11.0)

![image](https://user-images.githubusercontent.com/28896432/61593745-62e9da00-ac1e-11e9-8d5b-73e119e04e8c.png)
- word2vec이라는 디렉토리 생성후, README.md에서 언급한 구글드라이브에 있는 파일 2개를 다운받아서 word2vec 디렉토리로 옮겼습니다.
- [Google Drive Link](https://drive.google.com/drive/folders/1s3FPxHu1YvJnP49c5i76Vr1rY631ah_d?usp=sharing)

![image](https://user-images.githubusercontent.com/28896432/61593733-31710e80-ac1e-11e9-98d5-de91b670d465.png)
- 위의 사진은 python main.py를 한 결과입니다. 일단 윈도우로 돌렸을때는 잘 되었는데 리눅스는 제가 아직 테스트해보지 못했습니다. 테스트 해보고 다시 커멘트 달도록 하겠습니다:)

**Comment by monologg** [comment]
![image](https://user-images.githubusercontent.com/28896432/61594255-a6474700-ac24-11e9-8144-bf0c3037a442.png)
- gcp를 빌려서 ubuntu 16.04에서 테스트를 해봤는데 정상작동하는 것 같습니다.
- 혹시 pickle 파일을 Google drive 링크에서 다시 한번 받아주시고, 그 후 word2vec이란 폴더 만든 후 그 안에 두개의 pickle 파일을 넣고 다시 테스트해주실 수 있으신가요? 그렇게 해도 문제가 생긴다면 로그 올려주시면 다시 확인해보도록 하겠습니다:)

- config.py의 Config 클래스의 __init__ 함수에서 self.use_word_pretrained = False로 해놓으면 word_emb_dim_300.pkl 파일을 읽지 않습니다. 임시방편으로 이렇게 하고 돌리는 방법도 있을 것 같습니다.

**Comment by monologg** [comment]
참고로 config.py에 있는 세팅 그대로 할 시 GPU메모리가 터질껍니다.....
config.py의 Config 클래스의 init 함수에서 self.use_conv_model과 self.use_lm은 False로 해놓고 돌리는 것을 권장합니다. 실제로 이 두 개는 성능 향상에 극도로 미미했습니다. (word_pretrained_emb도 마찬가지였습니다.)

**Comment by wglee92** [comment]
연구실 서버를 사용하고 있는데 서버 문제였던것 같습니다! 
말씀하신 내용 참고하여 다른 환경에서 동작하니 정상작동 하였습니다! 
개인적인 문제로 번거롭게 해드린 꼴이 되었네요... 죄송합니다.
조만간 문제가 되었던 서버 환경을 게시하여 다른 분들도 참고할 수 있도록 하겠습니다.

좋은 코드 올려주셔서 감사합니다.
알려주신 파라미터도 상황에 맞춰 잘 사용하겠습니다 :)

**Comment by monologg** [comment]
정상 작동한다니 다행이네요:) 추후에 코드 Refactoring도 진행하도록 하겠습니다. 코드에 관심 가져주셔서 정말 감사합니다^^
